# Shopify App Configuration
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Presm DTF Shopify App"
client_id = "${SHOPIFY_API_KEY}"
application_url = "https://${REPL_SLUG}.${REPL_OWNER}.repl.co"
embedded = true

[access_scopes]
# Essential scopes for DTF app
scopes = "read_products,write_products,read_orders,write_orders,read_customers,read_inventory,write_inventory,read_fulfillments,write_fulfillments"

# Optional: Add these for advanced features
# scopes = "read_products,write_products,read_orders,write_orders,read_customers,read_inventory,write_inventory,read_fulfillments,write_fulfillments,read_files,write_files,read_draft_orders,write_draft_orders"

[auth]
redirect_urls = [
  "https://${REPL_SLUG}.${REPL_OWNER}.repl.co/api/auth/shopify/callback"
]

[webhooks]
api_version = "2024-10"

[[webhooks.subscriptions]]
topics = [ "orders/create" ]
uri = "/api/shopify/webhooks/order/created"

[[webhooks.subscriptions]]
topics = [ "orders/updated" ]
uri = "/api/shopify/webhooks/order/updated"

[pos]
embedded = false
